FROM ubuntu

MAINTAINER Tetricz

RUN apt-get update
RUN apt-get -y install lib32gcc1 wget
RUN apt-get -y install libfontconfig1 libpangocairo-1.0-0 libnss3 libgconf2-4 libxi6 libxcursor1 libxss1 libxcomposite1 libasound2 libxdamage1 libxtst6 libatk1.0-0 libxrandr2

ENV DATA="/opt"
ENV STEAMCMD="${DATA}/steamcmd"
ENV GAME_DIR="${DATA}/mordhau"
ENV GAME_ID="629800"
ENV VAC_PORT=27015
ENV GAME_PORT=7777
ENV VALIDATE=""
ENV UID=99
ENV GID=100

RUN mkdir $DATA
RUN mkdir $STEAMCMD
RUN mkdir $GAME_DIR
RUN useradd -d $DATA -s /bin/bash --uid $UID --gid $GID steam
RUN chown -R steam $DATA

RUN ulimit -n 1000000

ADD /scripts/ /opt/scripts/
RUN chmod -R 770 /opt/scripts/
RUN chown -R steam /opt/scripts
RUN cp -v /opt/scripts/updatemordahu.txt /opt/steamcmd/updatemordahu.txt
RUN cp -v /opt/scripts/validatemordahu.txt /opt/steamcmd/validatemordahu.txt

USER steam

ENTRYPOINT ["/opt/scripts/start-md-server.sh"]
