version: '3'
services:
    Mordhau1:
        restart: unless-stopped
        container_name: Mordhau1
        image: tetricz/mordhau-server

        volumes:
         - ./steamcmd:/serverdata/steamcmd
         - ./mordhau:/serverdata/mordhau
        environment:
         - PLAYER_COUNT=16
         - SERVER_NAME=
         - QUERYPORT=27015
         - GAME_PORT=7777
         - STEAMID64=
         - GAME_MODE=
         - SERVER=1
         - STEAM_CONNECT=True
        ports:
         - "7777:7777/udp"
         - "27015:27015/udp"
    Mordhau2:
        restart: unless-stopped
        container_name: Mordhau2
        image: tetricz/mordhau-server

        volumes:
         - ./steamcmd:/serverdata/steamcmd
         - ./mordhau:/serverdata/mordhau
        environment:
         - PLAYER_COUNT=16
         - SERVER_NAME=
         - QUERYPORT=27016
         - GAME_PORT=7778
         - STEAMID64=
         - GAME_MODE=DM
         - SERVER=2
         - STEAM_CONNECT=false
        ports:
         - "7778:7778/udp"
         - "27016:27016/udp"
    Mordhau3:
        restart: unless-stopped
        container_name: Mordhau3
        image: tetricz/mordhau-server

        volumes:
         - ./steamcmd:/serverdata/steamcmd
         - ./mordhau:/serverdata/mordhau
        env_file:
         server3-variables.env
        ports:
         - "7779:7779/udp"
         - "27017:27017/udp"
